
CREATE TABLE FUNCIONARIO(
    IDFUNCIONARIO SERIAL,
    CARGO VARCHAR(10) NOT NULL,
    SENHA VARCHAR(10) NOT NULL,
    ATIVO CHAR(1) NOT NULL DEFAULT 'N',
    ID_AGENDA INTEGER NOT NULL,
	ID_ENDERECO INTEGER NOT NULL
)

CREATE TABLE CONDOMINIO(
    IDCONDOMINIO SERIAL,
    ID_AGENDA INTEGER NOT NULL,
    ID_ADMINISTRADORA INTEGER,
    ID_CONTRATO INTEGER,
    ID_ENDERECO INTEGER NOT NULL
)

CREATE TABLE AGENDA(
    IDAGENDA SERIAL,
    NOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    TELEFONE VARCHAR(11) NOT NULL
)

CREATE TABLE ENDERECO(
    IDENDERECO SERIAL,
    RUA VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    NUMERO VARCHAR(4) NOT NULL,
    PRONT_REFERENCIA VARCHAR(30)
)

CREATE TABLE ADMINISTRADORA(
	IDADMINISTRADORA SERIAL,
	CNPJ VARCHAR(14) NOT NULL,
	ID_AGENDA INTEGER NOT NULL,
	ID_ENDERECO NOT NULL
)

CREATE TABLE CONTRATO(
	IDCONTRATO SERIAL,
	NUM_CONTRATO INTEGER
)

ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT PK_FUNCIONARIO 
PRIMARY KEY (IDFUNCIONARIO);

ALTER TABLE CONDOMINIO
ADD CONSTRAINT PK_CONDOMINIO
PRIMARY KEY (IDCONDOMINIO);

ALTER TABLE AGENDA
ADD CONSTRAINT PK_AGENDA
PRIMARY KEY (IDAGENDA);

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ENDERECO
PRIMARY KEY (IDENDERECO);

ALTER TABLE ADMINISTRADORA
ADD CONSTRAINT PK_ADMINISTRADORA
PRIMARY KEY (IDADMINISTRADORA);

ALTER TABLE CONTRATO
ADD CONSTRAINT PK_CONTRATO
PRIMARY KEY (IDCONTRATO);

ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA (IDAGENDA);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (IDENDERECO);

ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA (IDAGENDA);
ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_ADMINISTRADORA) REFERENCES ADMINISTRADORA (IDADMINISTRADORA);
ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (IDCONTRATO);
ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (IDENDERECO);

ALTER TABLE ADMINISTRADORA ADD FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA (IDAGENDA);
ALTER TABLE ADMINISTRADORA ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (IDENDERECO);



===================================================================================================
===================================================================================================
===================================================================================================
===================================================================================================
===================================================================================================
CREATE TABLE MUNICIPIO (
IDMUNICIPIO SERIAL,
COD_MUNICIPIO INTEGER NOT NULL,
NOME VARCHAR(50),
COD_UF INTEGER,
UF CHAR(2),
ATIVO CHAR (1)
);

CREATE TABLE BAIRRO (
IDBAIRRO SERIAL,
NOME VARCHAR(50) NOT NULL,
ID_MUNICIPIO INTEGER
);

CREATE TABLE EMPRESA (
IDEMPRESA SERIAL,
RAZAO_SOCIAL VARCHAR(50) NOT NULL UNIQUE,
NOME_FANTASIA VARCHAR(50) NOT NULL,
CNPJ VARCHAR(14) NOT NULL UNIQUE,
INSCRICAO_ESTADUAL VARCHAR(11) UNIQUE,
LOGRADOURO VARCHAR(50) NOT NULL,
NUMERO VARCHAR(6) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
ID_MUNICIPIO INTEGER NOT NULL,
TELEFONE VARCHAR(11)NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
LOGO VARCHAR (300) NOT NULL UNIQUE
);

CREATE TABLE ENTREGA (
IDENTREGA SERIAL,
ID_PEDIDO INTEGER NOT NULL,
CANCELADO CHAR(1) NOT NULL DEFAULT 'N',
DATA_ENTREGA VARCHAR(8)
);

CREATE TABLE DEVOLUCAO (
IDDEVOLUCAO SERIAL,
ID_PEDIDO INTEGER NOT NULL,
IDENTREGA INTEGER,
DATA_DEVOL VARCHAR(8) NOT NULL,
MOTIVO VARCHAR(250) NOT NULL,
OBS VARCHAR(250)
);

CREATE TABLE PEDIDO (
IDPEDIDO SERIAL,
NUN_PEDIDO INTEGER NOT NULL,
ID_EMPRESA INTEGER NOT NULL,
ID_USUARIO INTEGER NOT NULL,
ID_ESTOQUE INTEGER NOT NULL,
QUANTIDADE INTEGER,
ID_VLR INTEGER NOT NULL,
VALOR DECIMAL(6,2) NOT NULL,
DESCONTO DECIMAL (6,2),
VALOR_TOTAL DECIMAL (6,2) NOT NULL,
FORMA_PAGAMENTO CHAR(1) NOT NULL,
TROCO DECIMAL(6,2) DEFAULT '0.00',
DATA_VENDA VARCHAR(8) NOT NULL
);

CREATE TABLE RELA_CLIENTE (
IDRELATORIO SERIAL,
ID_USUARIO INTEGER NOT NULL,
ID_PEDIDO INTEGER NOT NULL,
SUGESTAO VARCHAR(200),
AVALIACAO SMALLINT NOT NULL
);

CREATE TABLE USUARIO (
IDUSUARIO SERIAL,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL UNIQUE,
LOGRADOURO VARCHAR(50) NOT NULL,
NUMERO VARCHAR(6) NOT NULL,
ID_BAIRRO INTEGER NOT NULL,
ID_MUNICIPIO INTEGER NOT NULL,
TELEFONE01 VARCHAR(11) NOT NULL,
TELEFONE02 VARCHAR(11),
EMAIL VARCHAR(50) NOT NULL UNIQUE,
REDE_SOCIAL CHAR(1),
WEB_ENDERECO VARCHAR(50) UNIQUE,
DATA_NASC VARCHAR(8) NOT NULL,
DATA_CADASTRO VARCHAR(8) NOT NULL,
/*LOGIN VARCHAR(50) NOT NULL UNIQUE,*/
SENHA VARCHAR(8) NOT NULL,
ATIVO CHAR(1),
ID_TIPO_ENTREGA INTEGER,
ID_LISTA_COMPRA INTEGER
);

CREATE TABLE TIPO_ENTREGA (
IDTIPO SERIAL,
DELIVERY CHAR(1)
);

CREATE TABLE ESTOQUE (
IDESTOQUE SERIAL,
ID_PRODUTO INTEGER NOT NULL,
ID_EMPRESA INTEGER NOT NULL,
ID_GRUPO INTEGER NOT NULL,
QUANT_ESTOQUE INTEGER,
VALOR DECIMAL(6,2),
SITUACAO CHAR(1),
PROMOCAO CHAR(1)
);

CREATE TABLE MARCA_PRODUTO (
IDMARCA SERIAL,
NOME VARCHAR(50) NOT NULL
);

CREATE TABLE GRUPO_PRODUTO (
IDGRUPO SERIAL,
NOME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE LISTA_COMPRA (
IDLISTCOMPRA SERIAL,
ID_USUARIO INTEGER NOT NULL,
ID_PRODUTO INTEGER NOT NULL,
NOME_LISTA VARCHAR(15) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
MERCADOS_DISPONIVEIS INTEGER,
MAIOR_VALOR DECIMAL(6,2),
MENOR_VALOR DECIMAL(6,2),
DATA_LISTA VARCHAR(8) NOT NULL,
TOTAL DECIMAL(6,2)
);

CREATE TABLE PRODUTO (
IDPRODUTO SERIAL,
CODIGO_BARRAS VARCHAR(50) UNIQUE,
FOTO VARCHAR (200),
DESCRICAO VARCHAR(50) NOT NULL,
CARACTERIS_PROD VARCHAR(200) NOT NULL,
TIPO_EMBALAGEM VARCHAR(20) NOT NULL,
ID_GRUPO INTEGER NOT NULL,
ID_MARCA INTEGER NOT NULL,
SITUACAO CHAR(1)
);

CREATE TABLE VLR_ENTREGA (
IDVLR SERIAL,
ID_EMPRESA INTEGER NOT NULL,
ID_BAIRRO INTEGER NOT NULL,
VALOR DECIMAL(6,2)
);

ALTER TABLE MUNICIPIO 
ADD CONSTRAINT PK_MUNICIPIO 
PRIMARY KEY (IDMUNICIPIO);

ALTER TABLE BAIRRO 
ADD CONSTRAINT PK_BAIRRO 
PRIMARY KEY (IDBAIRRO);

ALTER TABLE EMPRESA 
ADD CONSTRAINT PK_EMPRESA 
PRIMARY KEY (IDEMPRESA);

ALTER TABLE ENTREGA 
ADD CONSTRAINT PK_ENTREGA 
PRIMARY KEY (IDENTREGA);

ALTER TABLE DEVOLUCAO 
ADD CONSTRAINT PK_DEVOLUCAO 
PRIMARY KEY (IDDEVOLUCAO);

ALTER TABLE PEDIDO 
ADD CONSTRAINT PK_PEDIDO 
PRIMARY KEY (IDPEDIDO);

ALTER TABLE RELA_CLIENTE 
ADD CONSTRAINT PK_RELA_CLIENTE 
PRIMARY KEY (IDRELATORIO);

ALTER TABLE USUARIO 
ADD CONSTRAINT PK_USUARIO 
PRIMARY KEY (IDUSUARIO);

ALTER TABLE TIPO_ENTREGA 
ADD CONSTRAINT PK_TIPO_ENTREGA 
PRIMARY KEY (IDTIPO);

ALTER TABLE ESTOQUE 
ADD CONSTRAINT PK_ESTOQUE 
PRIMARY KEY (IDESTOQUE);

ALTER TABLE MARCA_PRODUTO 
ADD CONSTRAINT PK_MARCA_PRODUTO 
PRIMARY KEY (IDMARCA);

ALTER TABLE GRUPO_PRODUTO 
ADD CONSTRAINT PK_GRUPO 
PRIMARY KEY (IDGRUPO);

ALTER TABLE LISTA_COMPRA 
ADD CONSTRAINT PK_LIST_COMPRA 
PRIMARY KEY (IDLISTCOMPRA);

ALTER TABLE PRODUTO ADD 
CONSTRAINT PK_PRODUTO 
PRIMARY KEY (IDPRODUTO);

ALTER TABLE VLR_ENTREGA 
ADD CONSTRAINT PK_VLR_ENTREGA 
PRIMARY KEY (IDVLR);

ALTER TABLE BAIRRO ADD FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (IDMUNICIPIO);
ALTER TABLE EMPRESA ADD FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (IDMUNICIPIO);
ALTER TABLE ENTREGA ADD FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (IDPEDIDO);
ALTER TABLE DEVOLUCAO ADD FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (IDPEDIDO);
ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (IDEMPRESA);
ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_ESTOQUE) REFERENCES ESTOQUE (IDESTOQUE);
ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_VLR) REFERENCES VLR_ENTREGA (IDVLR);
ALTER TABLE RELA_CLIENTE ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE RELA_CLIENTE ADD FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (IDPEDIDO);
ALTER TABLE USUARIO ADD FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO (IDBAIRRO);
ALTER TABLE USUARIO ADD FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (IDMUNICIPIO);
ALTER TABLE USUARIO ADD FOREIGN KEY (ID_TIPO_ENTREGA) REFERENCES TIPO_ENTREGA (IDTIPO);
ALTER TABLE USUARIO ADD FOREIGN KEY (ID_LISTA_COMPRA) REFERENCES LISTA_COMPRA (IDLISTCOMPRA);
ALTER TABLE ESTOQUE ADD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (IDPRODUTO);
ALTER TABLE ESTOQUE ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (IDEMPRESA);
ALTER TABLE ESTOQUE ADD FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO_PRODUTO (IDGRUPO);
ALTER TABLE LISTA_COMPRA ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE LISTA_COMPRA ADD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (IDPRODUTO);
ALTER TABLE PRODUTO ADD FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO_PRODUTO (IDGRUPO);
ALTER TABLE PRODUTO ADD FOREIGN KEY (ID_MARCA) REFERENCES MARCA_PRODUTO (IDMARCA);
ALTER TABLE VLR_ENTREGA ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (IDEMPRESA);
ALTER TABLE VLR_ENTREGA ADD FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO (IDBAIRRO);

=============================================================================================
=============================================================================================
=============================================================================================
DROP TABLE BAIRRO, DEVOLUCAO, EMPRESA, ENTREGA, ESTOQUE, GRUPO_PRODUTO, LISTA_COMPRA, MARCA_PRODUTO, MUNICIPIO, PEDIDO, PRODUTO, RELA_CLIENTE, TIPO_ENTREGA, USUARIO, VLR_ENTREGA;
=============================================================================================
=============================================================================================
=============================================================================================

=============================================================================================

INSERT TIPO_ENTREGA:

INSERT INTO TIPO_ENTREGA (DELIVERY) VALUES ('D');
INSERT INTO TIPO_ENTREGA (DELIVERY) VALUES ('M');

=============================================================================================

INSERT MARCA_PRODUTO:

INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 1');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 2');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 3');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 4');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 5');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 6');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 7');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 8');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 9');
INSERT INTO MARCA_PRODUTO (NOME) VALUES ('MARCA PRODUTO 10');

=============================================================================================

INSERT GRUPO_PRODUTO:

INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 1');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 2');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 3');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 4');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 5');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 6');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 7');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 8');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 9');
INSERT INTO GRUPO_PRODUTO (NOME) VALUES ('GRUPO PRODUTO 10');

=============================================================================================

INSERT BAIRRO:

INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO UM', 49);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO DOIS', 88);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO TRÊZ', 90);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO QUATRO', 206);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO CINCO', 351);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO SEIS', 117);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO SETE', 946);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO OITO', 1190);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO NOVA', 897);
INSERT INTO BAIRRO (NOME, ID_MUNICIPIO) VALUES ('BAIRRO DEZ', 985);

=============================================================================================

INSERT EMPRESA:

INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 01',
	'MERCADO NUMERO UM',
	'12762144000550',
	'16500500',
	'RUA DO CENTRO',
	'500',
	'CENTRO',
	1,
	'8330652020',
	'EMPRESA01@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\01');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 02',
	'MERCADO NUMERO DOIS',
	'15762143000180',
	'16400400',
	'RUA DO CENTRO VIZIN',
	'600',
	'CENTRO',
	1,
	'8380502020',
	'EMPRESA02@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\02');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 3',
	'MERCADO NUMERO TRÊS',
	'12799944000150',
	'16580580',
	'RUA DO BAIRRO',
	'660',
	'MEDICI',
	1,
	'8320202020',
	'EMPRESA03@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\03');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 4',
	'MERCADO NUMERO QUATRO',
	'17700174000107',
	'96500500',
	'RUA JOSE FLOR',
	'354',
	'CRUZEIRO',
	1,
	'8330663191',
	'EMPRESA04@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\04');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 5',
	'MERCADO NUMERO CINCO',
	'12762144000950',
	'16500900',
	'RUA DO CENTRO',
	'100',
	'CENTRO',
	2,
	'8330652020',
	'EMPRESA05@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\05');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 6',
	'MERCADO NUMERO SEIS',
	'12762144000130',
	'16500510',
	'RUA DO CENTRO',
	'500',
	'CENTRO',
	1,
	'8330652020',
	'EMPRESA06@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\06');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 7',
	'MERCADO NUMERO SETE',
	'12762144000120',
	'16500520',
	'RUA DO CENTRO',
	'500',
	'CENTRO',
	1,
	'8330652020',
	'EMPRESA07@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\07');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 8',
	'MERCADO NUMERO OITO',
	'12762144000990',
	'16500530',
	'RUA DO CENTRO',
	'500',
	'CENTRO',
	1,
	'8330652020',
	'EMPRESA08@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\08');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 9',
	'MERCADO NUMERO NOVE',
	'12762144000850',
	'16500540',
	'RUA DO CENTRO',
	'500',
	'CENTRO',
	1,
	'8330652020',
	'EMPRESA09@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\09');
INSERT INTO EMPRESA (
	RAZAO_SOCIAL,
	NOME_FANTASIA,
	CNPJ,
	INSCRICAO_ESTADUAL,
	LOGRADOURO,
	NUMERO,
	BAIRRO,
	ID_MUNICIPIO,
	TELEFONE,
	EMAIL,
	LOGO) 
	VALUES (
	'EMPRESA 10',
	'MERCADO NUMERO DEZ',
	'12762144000150',
	'16500550',
	'RUA DO CENTRO',
	'500',
	'CENTRO',
	1,
	'8330652020',
	'EMPRESA10@GMAIL.COM',
	'D:\Thiago\Documentos\Empresas\Delivery Mercado\Imagens\#Imagens em Uso\10');
	
=============================================================================================

INSERT PRODUTO

INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123456789',
	'C:MEU PC/FOTO-1',
	'ARROZ',
	'PRODUTO PRONTO PARA COZINHAR FEITO COM AMOR',
	'PC',
	1,
	1,
	'1'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123456799',
	'C:MEU PC/FOTO-2',
	'FEIJÃO',
	'PRODUTO PRONTO PARA COZINHAR FEITO COM AMOR',
	'PC',
	1,
	1,
	'1'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123456999',
	'C:MEU PC/FOTO-3',
	'MACARRÃO',
	'PRODUTO PRONTO PARA COZINHAR FEITO COM AMOR',
	'PC',
	1,
	1,
	'0'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123459999',
	'C:MEU PC/FOTO-4',
	'CARNE',
	'PRODUTO MUITO BOM',
	'KG',
	2,
	2,
	'1'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123499999',
	'C:MEU PC/FOTO-5',
	'FRANGO',
	'PRODUTO AINDA VIVO PRONTO PARA ABATE',
	'KG',
	4,
	4,
	'0'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123999999',
	'C:MEU PC/FOTO-6',
	'CAIXA CHOCOLATE',
	'CAIXA COM 50 DOCINHOS MARAVILHOSOS',
	'CX',
	2,
	3,
	'1'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'129999999',
	'C:MEU PC/FOTO-7',
	'SABONETE',
	'VAI TI DEIXAR LIMPINHO',
	'UN',
	3,
	1,
	'0'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'199999999',
	'C:MEU PC/FOTO-8',
	'ARROZ',
	'PRODUTO PRONTO PARA COZINHAR FEITO COM AMOR',
	'PC',
	1,
	1,
	'1'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'999999999',
	'C:MEU PC/FOTO-9',
	'BOI',
	'AINDA VIVO E SEM CHIFRES',
	'KG',
	4,
	4,
	'0'
);
INSERT INTO PRODUTO (
	CODIGO_BARRAS,
	FOTO,
	DESCRICAO,
	CARACTERIS_PROD,
	TIPO_EMBALAGEM,
	ID_GRUPO,
	ID_MARCA,
	SITUACAO
) VALUES (
	'123456780',
	'C:MEU PC/FOTO-1',
	'CAFE',
	'TORRADO COM AMOR E SUOR',
	'PC',
	1,
	1,
	'1'
);

=============================================================================================

INSERT ESTOQUE

INSERT INTO ESTOQUE (
	ID_PRODUTO,
	ID_EMPRESA,
	ID_GRUPO,
	QUANT_ESTOQUE,
	VALOR,
	SITUACAO,
	PROMOCAO
) VALUES (
	1,
	5,
	1,
	20,
	15.99,
	'1',
	'1'
);
INSERT INTO ESTOQUE (
	ID_PRODUTO,
	ID_EMPRESA,
	ID_GRUPO,
	QUANT_ESTOQUE,
	VALOR,
	SITUACAO,
	PROMOCAO
) VALUES (
	5,
	8,
	2,
	15,
	11.99,
	'1',
	'0'
);
INSERT INTO ESTOQUE (
	ID_PRODUTO,
	ID_EMPRESA,
	ID_GRUPO,
	QUANT_ESTOQUE,
	VALOR,
	SITUACAO,
	PROMOCAO
) VALUES (
	3,
	5,
	3,
	2,
	1.99,
	'1',
	'1'
);
INSERT INTO ESTOQUE (
	ID_PRODUTO,
	ID_EMPRESA,
	ID_GRUPO,
	QUANT_ESTOQUE,
	VALOR,
	SITUACAO,
	PROMOCAO
) VALUES (
	10,
	8,
	1,
	3,
	49.99,
	'0',
	'0'
);
INSERT INTO ESTOQUE (
	ID_PRODUTO,
	ID_EMPRESA,
	ID_GRUPO,
	QUANT_ESTOQUE,
	VALOR,
	SITUACAO,
	PROMOCAO
) VALUES (
	9,
	3,
	2,
	80,
	13.99,
	'1',
	'0'
);

=============================================================================================

INSERT VLR_ENTREGA

INSERT INTO VLR_ENTREGA (
	ID_EMPRESA,
	ID_BAIRRO,
	VALOR
) VALUES (
	3,
	3,
	15.00
);
INSERT INTO VLR_ENTREGA (
	ID_EMPRESA,
	ID_BAIRRO,
	VALOR
) VALUES (
	5,
	1,
	25.00
);
INSERT INTO VLR_ENTREGA (
	ID_EMPRESA,
	ID_BAIRRO,
	VALOR
) VALUES (
	7,
	2,
	10.00
);
INSERT INTO VLR_ENTREGA (
	ID_EMPRESA,
	ID_BAIRRO,
	VALOR
) VALUES (
	5,
	2,
	20.00
);
INSERT INTO VLR_ENTREGA (
	ID_EMPRESA,
	ID_BAIRRO,
	VALOR
) VALUES (
	7,
	1,
	15.00
);

=============================================================================================

INSERT USUARIO

INSERT INTO USUARIO (
	NOME,
	CPF,
	LOGRADOURO,
	NUMERO,
	ID_BAIRRO,
	ID_MUNICIPIO,
	TELEFONE01,
	TELEFONE02,
	EMAIL,
	REDE_SOCIAL,
	WEB_ENDERECO,
	DATA_NASC,
	DATA_CADASTRO,
	/*LOGIN,*/
	SENHA,
	ATIVO,
	ID_TIPO_ENTREGA,
	ID_LISTA_COMPRA
) VALUES (
	'THIAGO BEZERRA',
	'09878855457',
	'RUA JOAO DA CUNHA LIMA',
	'570',
	1,
	1,
	'83999696093',
	NULL,
	'B.THIAGO2404@GMAIL.COM',
	'S',
	'@B.THIAGO2404',
	'24041992',
	'01022019',
	/*'ATHOS',*/
	'123456',
	'1',
	1,
	NULL
);

=============================================================================================

INSERT PEDIDO

INSERT INTO PEDIDO (
	NUN_PEDIDO,
	ID_EMPRESA,
	ID_USUARIO,
	ID_ESTOQUE,
	QUANTIDADE,
	ID_VLR,
	VALOR,
	DESCONTO,
	VALOR_TOTAL,
	FORMA_PAGAMENTO,
	TROCO,
	DATA_VENDA
) VALUES (
	1,
	5,
	1,
	5,
	20,
	1,
	294.80,
	4.80,
	290.00,
	'D',
	10.00,
	01022019	
);
INSERT INTO PEDIDO (
	NUN_PEDIDO,
	ID_EMPRESA,
	ID_USUARIO,
	ID_ESTOQUE,
	QUANTIDADE,
	ID_VLR,
	VALOR,
	DESCONTO,
	VALOR_TOTAL,
	FORMA_PAGAMENTO,
	TROCO,
	DATA_VENDA
) VALUES (
	2,
	2,
	1,
	1,
	2,
	1,
	31.98,
	1.98,
	30.00,
	'D',
	20.00,
	01022019	
);

=============================================================================================

INSERT ENTREGA

INSERT INTO ENTREGA (
	ID_PEDIDO,
	CANCELADO,
	DATA_ENTREGA
) VALUES (
	1,
	'N',
	'01022019'
);
INSERT INTO ENTREGA (
	ID_PEDIDO,
	CANCELADO,
	DATA_ENTREGA
) VALUES (
	2,
	'S',
	'NULL'
);

=============================================================================================

INSERT DEVOLUCAO

INSERT INTO DEVOLUCAO (
	ID_PEDIDO,
	DATA_DEVOL,
	MOTIVO,
	OBS
) VALUES (
	2,
	'05022019',
	'MERCADORIA CHEGOU COM DEFEITO',
	'TREMENDA MERDA'
);

=============================================================================================

INSERT RELA_CLIENTE

INSERT INTO RELA_CLIENTE (
	ID_USUARIO,
	ID_PEDIDO,
	SUGESTAO,
	AVALIACAO
) VALUES (
	1,
	1,
	'TUDO OK MUITO SATISFEITO',
	5
);
INSERT INTO RELA_CLIENTE (
	ID_USUARIO,
	ID_PEDIDO,
	SUGESTAO,
	AVALIACAO
) VALUES (
	1,
	2,
	'INFELIZMENTE DEU ERRO',
	2
);

=============================================================================================

INSERT LISTA_COMPRA

INSERT INTO LISTA_COMPRA (
	ID_USUARIO,
	ID_PRODUTO,
	NOME_LISTA,
	QUANTIDADE,
	MERCADOS_DISPONIVEIS,
	MAIOR_VALOR,
	MENOR_VALOR,
	DATA_LISTA,
	TOTAL
) VALUES (
	1,
	5,
	'CHURRASCO',
	2,
	8,
	15.00,
	12.50,
	'01022019',
	25.00
);

=============================================================================================
