
CREATE TABLE FUNCIONARIO(
    IDFUNCIONARIO SERIAL,
    CARGO VARCHAR(10) NOT NULL,
    SENHA VARCHAR(10) NOT NULL,
    ATIVO CHAR(1) NOT NULL DEFAULT 'N',
    ID_AGENDA INTEGER NOT NULL,
	ID_ENDERECO INTEGER NOT NULL
)

CREATE TABLE CONDOMINIO(
    IDCONDOMINIO SERIAL,
    ID_AGENDA INTEGER NOT NULL,
    ID_ADMINISTRADORA INTEGER,
    ID_CONTRATO INTEGER,
    ID_ENDERECO INTEGER NOT NULL
)

CREATE TABLE AGENDA(
    IDAGENDA SERIAL,
    NOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    TELEFONE VARCHAR(11) NOT NULL
)

CREATE TABLE ENDERECO(
    IDENDERECO SERIAL,
    RUA VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    NUMERO VARCHAR(4) NOT NULL,
    PRONT_REFERENCIA VARCHAR(30)
)

CREATE TABLE ADMINISTRADORA(
	IDADMINISTRADORA SERIAL,
	CNPJ VARCHAR(14) NOT NULL,
	ID_AGENDA INTEGER NOT NULL,
	ID_ENDERECO NOT NULL
)

CREATE TABLE CONTRATO(
	IDCONTRATO SERIAL,
	NUM_CONTRATO INTEGER
)

ALTER TABLE FUNCIONARIO 
ADD CONSTRAINT PK_FUNCIONARIO 
PRIMARY KEY (IDFUNCIONARIO);

ALTER TABLE CONDOMINIO
ADD CONSTRAINT PK_CONDOMINIO
PRIMARY KEY (IDCONDOMINIO);

ALTER TABLE AGENDA
ADD CONSTRAINT PK_AGENDA
PRIMARY KEY (IDAGENDA);

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ENDERECO
PRIMARY KEY (IDENDERECO);

ALTER TABLE ADMINISTRADORA
ADD CONSTRAINT PK_ADMINISTRADORA
PRIMARY KEY (IDADMINISTRADORA);

ALTER TABLE CONTRATO
ADD CONSTRAINT PK_CONTRATO
PRIMARY KEY (IDCONTRATO);

ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA (IDAGENDA);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (IDENDERECO);

ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA (IDAGENDA);
ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_ADMINISTRADORA) REFERENCES ADMINISTRADORA (IDADMINISTRADORA);
ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (IDCONTRATO);
ALTER TABLE CONDOMINIO ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (IDENDERECO);

ALTER TABLE ADMINISTRADORA ADD FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA (IDAGENDA);
ALTER TABLE ADMINISTRADORA ADD FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (IDENDERECO);
